# Generated by Django 3.0.7 on 2020-11-21 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0005_studentresult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationstaffs',
            old_name='stafff_id',
            new_name='staff_id',
        ),
    ]
